# ++ monobiome scheme file ++
# ++ generated CLI @ 1.5.0 ++
version      = "1.5.0"
mode         = "dark"
biome        = "moorland"
metric       = "oklch"
distance     = "0.42"
l_base       = "20"
l_step       = "5"
fg_gap       = "50"
grey_gap     = "30"
term_fg_gap  = "65"
bg0          = "f{{moorland.l20}}"
bg1          = "f{{moorland.l25}}"
bg2          = "f{{moorland.l30}}"
bg3          = "f{{moorland.l35}}"
fg3          = "f{{moorland.l70}}"
fg2          = "f{{moorland.l75}}"
fg1          = "f{{moorland.l80}}"
fg0          = "f{{moorland.l85}}"
black        = "f{{moorland.l20}}"
grey         = "f{{moorland.l50}}"
white        = "f{{moorland.l75}}"
red          = "f{{red.l59}}"
orange       = "f{{orange.l61}}"
yellow       = "f{{yellow.l62}}"
green        = "f{{green.l61}}"
cyan         = "f{{cyan.l61}}"
blue         = "f{{blue.l60}}"
violet       = "f{{violet.l60}}"
magenta      = "f{{orange.l61}}"

[term]
background   = "f{{moorland.l25}}"
selection_bg = "f{{moorland.l30}}"
selection_fg = "f{{moorland.l85}}"
foreground   = "f{{moorland.l90}}"
cursor       = "f{{moorland.l85}}"
cursor_text  = "f{{moorland.l30}}"

[term.normal]
black        = "f{{moorland.l25}}"
grey         = "f{{moorland.l55}}"
white        = "f{{moorland.l80}}"
red          = "f{{red.l64}}"
yellow       = "f{{yellow.l67}}"
green        = "f{{green.l66}}"
cyan         = "f{{blue.l65}}"
blue         = "f{{blue.l65}}"
magenta      = "f{{orange.l66}}"

[term.bright]
black        = "f{{moorland.l35}}"
grey         = "f{{moorland.l65}}"
white        = "f{{moorland.l90}}"
red          = "f{{red.l75}}"
yellow       = "f{{yellow.l77}}"
green        = "f{{green.l76}}"
cyan         = "f{{blue.l76}}"
blue         = "f{{blue.l76}}"
magenta      = "f{{orange.l76}}"

[vim]
bg0          = "f{{moorland.l25}}"
bg1          = "f{{moorland.l30}}"
bg2          = "f{{moorland.l35}}"
bg3          = "f{{moorland.l40}}"
fg3          = "f{{moorland.l75}}"
fg2          = "f{{moorland.l80}}"
fg1          = "f{{moorland.l85}}"
fg0          = "f{{moorland.l90}}"
black        = "f{{moorland.l25}}"
grey         = "f{{moorland.l55}}"
white        = "f{{moorland.l80}}"
red          = "f{{red.l64}}"
orange       = "f{{orange.l66}}"
yellow       = "f{{yellow.l67}}"
green        = "f{{green.l66}}"
cyan         = "f{{green.l66}}"
blue         = "f{{blue.l65}}"
violet       = "f{{blue.l65}}"
magenta      = "f{{red.l64}}"