[alpine]
l10 = "#030303"
l11 = "#040404"
l12 = "#060606"
l13 = "#070707"
l14 = "#090909"
l15 = "#0b0b0b"
l16 = "#0d0d0d"
l17 = "#0f0f0f"
l18 = "#121212"
l19 = "#141414"
l20 = "#161616"
l21 = "#181818"
l22 = "#1b1b1b"
l23 = "#1d1d1d"
l24 = "#1f1f1f"
l25 = "#222222"
l26 = "#242424"
l27 = "#262626"
l28 = "#292929"
l29 = "#2b2b2b"
l30 = "#2e2e2e"
l31 = "#303030"
l32 = "#333333"
l33 = "#353535"
l34 = "#383838"
l35 = "#3a3a3a"
l36 = "#3d3d3d"
l37 = "#404040"
l38 = "#424242"
l39 = "#454545"
l40 = "#484848"
l41 = "#4a4a4a"
l42 = "#4d4d4d"
l43 = "#505050"
l44 = "#525252"
l45 = "#555555"
l46 = "#585858"
l47 = "#5b5b5b"
l48 = "#5d5d5d"
l49 = "#606060"
l50 = "#636363"
l51 = "#666666"
l52 = "#696969"
l53 = "#6c6c6c"
l54 = "#6f6f6f"
l55 = "#717171"
l56 = "#747474"
l57 = "#777777"
l58 = "#7a7a7a"
l59 = "#7d7d7d"
l60 = "#808080"
l61 = "#838383"
l62 = "#868686"
l63 = "#898989"
l64 = "#8c8c8c"
l65 = "#8f8f8f"
l66 = "#929292"
l67 = "#959595"
l68 = "#989898"
l69 = "#9b9b9b"
l70 = "#9e9e9e"
l71 = "#a1a1a1"
l72 = "#a4a4a4"
l73 = "#a8a8a8"
l74 = "#ababab"
l75 = "#aeaeae"
l76 = "#b1b1b1"
l77 = "#b4b4b4"
l78 = "#b7b7b7"
l79 = "#bababa"
l80 = "#bebebe"
l81 = "#c1c1c1"
l82 = "#c4c4c4"
l83 = "#c7c7c7"
l84 = "#cacaca"
l85 = "#cecece"
l86 = "#d1d1d1"
l87 = "#d4d4d4"
l88 = "#d7d7d7"
l89 = "#dbdbdb"
l90 = "#dedede"
l91 = "#e1e1e1"
l92 = "#e4e4e4"
l93 = "#e8e8e8"
l94 = "#ebebeb"
l95 = "#eeeeee"
l96 = "#f2f2f2"
l97 = "#f5f5f5"
l98 = "#f8f8f8"

[badlands]
l10 = "#060302"
l11 = "#070303"
l12 = "#090504"
l13 = "#0b0605"
l14 = "#0d0807"
l15 = "#0f0909"
l16 = "#120c0b"
l17 = "#140e0d"
l18 = "#16100f"
l19 = "#181211"
l20 = "#1b1413"
l21 = "#1d1615"
l22 = "#1f1918"
l23 = "#221b1a"
l24 = "#241d1c"
l25 = "#27201f"
l26 = "#292221"
l27 = "#2c2523"
l28 = "#2e2726"
l29 = "#312928"
l30 = "#332c2b"
l31 = "#362e2d"
l32 = "#383130"
l33 = "#3b3332"
l34 = "#3d3635"
l35 = "#403837"
l36 = "#433b3a"
l37 = "#453e3c"
l38 = "#48403f"
l39 = "#4b4342"
l40 = "#4d4644"
l41 = "#504847"
l42 = "#534b4a"
l43 = "#564e4c"
l44 = "#58504f"
l45 = "#5b5352"
l46 = "#5e5654"
l47 = "#615957"
l48 = "#645b5a"
l49 = "#675e5d"
l50 = "#696160"
l51 = "#6c6462"
l52 = "#6f6765"
l53 = "#726a68"
l54 = "#756c6b"
l55 = "#786f6e"
l56 = "#7b7271"
l57 = "#7e7574"
l58 = "#817877"
l59 = "#847b79"
l60 = "#877e7c"
l61 = "#8a817f"
l62 = "#8d8482"
l63 = "#908785"
l64 = "#938a88"
l65 = "#968d8b"
l66 = "#99908e"
l67 = "#9c9391"
l68 = "#9f9694"
l69 = "#a29997"
l70 = "#a59c9a"
l71 = "#a89f9d"
l72 = "#aba2a1"
l73 = "#aea5a4"
l74 = "#b2a8a7"
l75 = "#b5abaa"
l76 = "#b8afad"
l77 = "#bbb2b0"
l78 = "#beb5b3"
l79 = "#c1b8b6"
l80 = "#c5bbba"
l81 = "#c8bebd"
l82 = "#cbc2c0"
l83 = "#cec5c3"
l84 = "#d2c8c6"
l85 = "#d5cbca"
l86 = "#d8cecd"
l87 = "#dbd2d0"
l88 = "#dfd5d3"
l89 = "#e2d8d7"
l90 = "#e5dbda"
l91 = "#e8dfdd"
l92 = "#ece2e0"
l93 = "#efe5e4"
l94 = "#f2e9e7"
l95 = "#f6ecea"
l96 = "#f9efee"
l97 = "#fcf3f1"
l98 = "#fff6f5"

[chaparral]
l10 = "#050301"
l11 = "#070402"
l12 = "#080503"
l13 = "#0a0704"
l14 = "#0c0805"
l15 = "#0f0a07"
l16 = "#110c09"
l17 = "#130e0b"
l18 = "#15110d"
l19 = "#17130f"
l20 = "#1a1511"
l21 = "#1c1713"
l22 = "#1e1a15"
l23 = "#211c18"
l24 = "#231e1a"
l25 = "#26211c"
l26 = "#28231f"
l27 = "#2a2521"
l28 = "#2d2823"
l29 = "#2f2a26"
l30 = "#322d28"
l31 = "#342f2b"
l32 = "#37322d"
l33 = "#3a3430"
l34 = "#3c3732"
l35 = "#3f3935"
l36 = "#413c37"
l37 = "#443f3a"
l38 = "#47413c"
l39 = "#49443f"
l40 = "#4c4642"
l41 = "#4f4944"
l42 = "#524c47"
l43 = "#544f4a"
l44 = "#57514c"
l45 = "#5a544f"
l46 = "#5d5752"
l47 = "#5f5a55"
l48 = "#625c57"
l49 = "#655f5a"
l50 = "#68625d"
l51 = "#6b6560"
l52 = "#6e6863"
l53 = "#716a65"
l54 = "#736d68"
l55 = "#76706b"
l56 = "#79736e"
l57 = "#7c7671"
l58 = "#7f7974"
l59 = "#827c77"
l60 = "#857f7a"
l61 = "#88827d"
l62 = "#8b8580"
l63 = "#8e8882"
l64 = "#918b85"
l65 = "#948e88"
l66 = "#97918b"
l67 = "#9a948e"
l68 = "#9d9791"
l69 = "#a09a95"
l70 = "#a49d98"
l71 = "#a7a09b"
l72 = "#aaa39e"
l73 = "#ada6a1"
l74 = "#b0a9a4"
l75 = "#b3ada7"
l76 = "#b6b0aa"
l77 = "#bab3ad"
l78 = "#bdb6b0"
l79 = "#c0b9b3"
l80 = "#c3bcb7"
l81 = "#c6bfba"
l82 = "#c9c3bd"
l83 = "#cdc6c0"
l84 = "#d0c9c3"
l85 = "#d3ccc7"
l86 = "#d6d0ca"
l87 = "#dad3cd"
l88 = "#ddd6d0"
l89 = "#e0d9d3"
l90 = "#e4ddd7"
l91 = "#e7e0da"
l92 = "#eae3dd"
l93 = "#ede6e1"
l94 = "#f1eae4"
l95 = "#f4ede7"
l96 = "#f7f0ea"
l97 = "#fbf4ee"
l98 = "#fef7f1"

[savanna]
l10 = "#040301"
l11 = "#050502"
l12 = "#060603"
l13 = "#080704"
l14 = "#0a0905"
l15 = "#0c0b06"
l16 = "#0e0e08"
l17 = "#10100a"
l18 = "#12120c"
l19 = "#14140e"
l20 = "#171611"
l21 = "#191913"
l22 = "#1b1b15"
l23 = "#1e1d17"
l24 = "#20201a"
l25 = "#22221c"
l26 = "#25241e"
l27 = "#272721"
l28 = "#2a2923"
l29 = "#2c2c25"
l30 = "#2f2e28"
l31 = "#31312a"
l32 = "#34332d"
l33 = "#36362f"
l34 = "#393832"
l35 = "#3b3b34"
l36 = "#3e3d37"
l37 = "#404039"
l38 = "#43433c"
l39 = "#46453f"
l40 = "#484841"
l41 = "#4b4b44"
l42 = "#4e4d47"
l43 = "#515049"
l44 = "#53534c"
l45 = "#56564f"
l46 = "#595851"
l47 = "#5c5b54"
l48 = "#5e5e57"
l49 = "#61615a"
l50 = "#64645d"
l51 = "#67665f"
l52 = "#6a6962"
l53 = "#6d6c65"
l54 = "#6f6f68"
l55 = "#72726b"
l56 = "#75756e"
l57 = "#787870"
l58 = "#7b7b73"
l59 = "#7e7e76"
l60 = "#818179"
l61 = "#84847c"
l62 = "#87877f"
l63 = "#8a8a82"
l64 = "#8d8d85"
l65 = "#909088"
l66 = "#93938b"
l67 = "#96968e"
l68 = "#999991"
l69 = "#9c9c94"
l70 = "#9f9f97"
l71 = "#a2a29a"
l72 = "#a5a59d"
l73 = "#a9a8a0"
l74 = "#acaba3"
l75 = "#afaea7"
l76 = "#b2b1aa"
l77 = "#b5b5ad"
l78 = "#b8b8b0"
l79 = "#bbbbb3"
l80 = "#bfbeb6"
l81 = "#c2c1b9"
l82 = "#c5c5bd"
l83 = "#c8c8c0"
l84 = "#cbcbc3"
l85 = "#cfcec6"
l86 = "#d2d1c9"
l87 = "#d5d5cd"
l88 = "#d8d8d0"
l89 = "#dcdbd3"
l90 = "#dfded6"
l91 = "#e2e2da"
l92 = "#e5e5dd"
l93 = "#e9e8e0"
l94 = "#ecece3"
l95 = "#efefe7"
l96 = "#f3f2ea"
l97 = "#f6f6ed"
l98 = "#f9f9f1"

[grassland]
l10 = "#020402"
l11 = "#030503"
l12 = "#040704"
l13 = "#050805"
l14 = "#060a07"
l15 = "#080c09"
l16 = "#0a0f0b"
l17 = "#0c110d"
l18 = "#0e130f"
l19 = "#111511"
l20 = "#131713"
l21 = "#151a15"
l22 = "#171c18"
l23 = "#1a1e1a"
l24 = "#1c211c"
l25 = "#1e231f"
l26 = "#212621"
l27 = "#232823"
l28 = "#252a26"
l29 = "#282d28"
l30 = "#2a2f2b"
l31 = "#2d322d"
l32 = "#2f3430"
l33 = "#323732"
l34 = "#343a35"
l35 = "#373c37"
l36 = "#393f3a"
l37 = "#3c413c"
l38 = "#3f443f"
l39 = "#414742"
l40 = "#444944"
l41 = "#474c47"
l42 = "#494f4a"
l43 = "#4c524c"
l44 = "#4f544f"
l45 = "#515752"
l46 = "#545a55"
l47 = "#575d57"
l48 = "#5a5f5a"
l49 = "#5c625d"
l50 = "#5f6560"
l51 = "#626863"
l52 = "#656b65"
l53 = "#686e68"
l54 = "#6b706b"
l55 = "#6d736e"
l56 = "#707671"
l57 = "#737974"
l58 = "#767c77"
l59 = "#797f7a"
l60 = "#7c827d"
l61 = "#7f857f"
l62 = "#828882"
l63 = "#858b85"
l64 = "#888e88"
l65 = "#8b918b"
l66 = "#8e948e"
l67 = "#919791"
l68 = "#949a94"
l69 = "#979d98"
l70 = "#9aa09b"
l71 = "#9da39e"
l72 = "#a0a7a1"
l73 = "#a3aaa4"
l74 = "#a6ada7"
l75 = "#a9b0aa"
l76 = "#adb3ad"
l77 = "#b0b6b0"
l78 = "#b3b9b3"
l79 = "#b6bdb7"
l80 = "#b9c0ba"
l81 = "#bcc3bd"
l82 = "#c0c6c0"
l83 = "#c3c9c3"
l84 = "#c6cdc6"
l85 = "#c9d0ca"
l86 = "#ccd3cd"
l87 = "#d0d6d0"
l88 = "#d3dad3"
l89 = "#d6ddd7"
l90 = "#d9e0da"
l91 = "#dde3dd"
l92 = "#e0e7e0"
l93 = "#e3eae4"
l94 = "#e6ede7"
l95 = "#eaf1ea"
l96 = "#edf4ee"
l97 = "#f0f7f1"
l98 = "#f4fbf4"

[tundra]
l10 = "#020306"
l11 = "#030408"
l12 = "#040609"
l13 = "#05070c"
l14 = "#07090e"
l15 = "#090b10"
l16 = "#0b0d12"
l17 = "#0d0f14"
l18 = "#0f1217"
l19 = "#111419"
l20 = "#13161b"
l21 = "#16181d"
l22 = "#181b20"
l23 = "#1a1d22"
l24 = "#1c1f25"
l25 = "#1f2227"
l26 = "#212429"
l27 = "#23272c"
l28 = "#26292e"
l29 = "#282b31"
l30 = "#2b2e33"
l31 = "#2d3036"
l32 = "#303339"
l33 = "#32353b"
l34 = "#35383e"
l35 = "#373b40"
l36 = "#3a3d43"
l37 = "#3d4046"
l38 = "#3f4248"
l39 = "#42454b"
l40 = "#44484e"
l41 = "#474a51"
l42 = "#4a4d53"
l43 = "#4c5056"
l44 = "#4f5359"
l45 = "#52555c"
l46 = "#55585e"
l47 = "#575b61"
l48 = "#5a5e64"
l49 = "#5d6167"
l50 = "#60636a"
l51 = "#63666d"
l52 = "#65696f"
l53 = "#686c72"
l54 = "#6b6f75"
l55 = "#6e7278"
l56 = "#71757b"
l57 = "#74787e"
l58 = "#777a81"
l59 = "#7a7d84"
l60 = "#7d8087"
l61 = "#80838a"
l62 = "#82868d"
l63 = "#858990"
l64 = "#888c93"
l65 = "#8b8f96"
l66 = "#8e9299"
l67 = "#91959c"
l68 = "#95989f"
l69 = "#989ba2"
l70 = "#9b9fa5"
l71 = "#9ea2a9"
l72 = "#a1a5ac"
l73 = "#a4a8af"
l74 = "#a7abb2"
l75 = "#aaaeb5"
l76 = "#adb1b8"
l77 = "#b0b4bb"
l78 = "#b3b8bf"
l79 = "#b7bbc2"
l80 = "#babec5"
l81 = "#bdc1c8"
l82 = "#c0c4cb"
l83 = "#c3c7cf"
l84 = "#c7cbd2"
l85 = "#caced5"
l86 = "#cdd1d8"
l87 = "#d0d4dc"
l88 = "#d3d8df"
l89 = "#d7dbe2"
l90 = "#dadee6"
l91 = "#dde1e9"
l92 = "#e1e5ec"
l93 = "#e4e8ef"
l94 = "#e7ebf3"
l95 = "#eaeff6"
l96 = "#eef2f9"
l97 = "#f1f5fd"
l98 = "#f5f9ff"

[red]
l10 = "#0d0000"
l11 = "#100000"
l12 = "#140000"
l13 = "#170000"
l14 = "#1b0000"
l15 = "#1f0000"
l16 = "#220000"
l17 = "#260000"
l18 = "#2a0000"
l19 = "#2e0100"
l20 = "#320101"
l21 = "#360101"
l22 = "#3a0101"
l23 = "#3e0101"
l24 = "#420201"
l25 = "#460201"
l26 = "#4a0202"
l27 = "#4e0302"
l28 = "#530302"
l29 = "#570403"
l30 = "#5b0403"
l31 = "#5f0503"
l32 = "#640604"
l33 = "#680705"
l34 = "#6c0805"
l35 = "#710906"
l36 = "#750b07"
l37 = "#7a0c08"
l38 = "#7e0e09"
l39 = "#820f0a"
l40 = "#87110c"
l41 = "#8b130d"
l42 = "#90150f"
l43 = "#941710"
l44 = "#981912"
l45 = "#9d1b13"
l46 = "#a11d15"
l47 = "#a51f17"
l48 = "#aa2119"
l49 = "#ae241b"
l50 = "#b2271d"
l51 = "#b62920"
l52 = "#ba2c22"
l53 = "#be2f24"
l54 = "#c23227"
l55 = "#c6352a"
l56 = "#ca382d"
l57 = "#ce3c30"
l58 = "#d13f33"
l59 = "#d54336"
l60 = "#d84739"
l61 = "#db4b3d"
l62 = "#de4f40"
l63 = "#e15344"
l64 = "#e45748"
l65 = "#e65b4c"
l66 = "#e96050"
l67 = "#eb6455"
l68 = "#ee6959"
l69 = "#f06d5d"
l70 = "#f27262"
l71 = "#f47666"
l72 = "#f57b6b"
l73 = "#f78070"
l74 = "#f98475"
l75 = "#fa8979"
l76 = "#fb8e7e"
l77 = "#fc9283"
l78 = "#fe9788"
l79 = "#ff9c8d"
l80 = "#ffa193"
l81 = "#ffa699"
l82 = "#ffab9e"
l83 = "#ffb0a4"
l84 = "#ffb5aa"
l85 = "#ffbaaf"
l86 = "#ffbfb5"
l87 = "#ffc4ba"
l88 = "#ffc8c0"
l89 = "#ffcdc5"
l90 = "#ffd2ca"
l91 = "#ffd6d0"
l92 = "#ffdbd5"
l93 = "#ffe0da"
l94 = "#ffe4e0"
l95 = "#ffe9e5"
l96 = "#ffedea"
l97 = "#fff2ef"
l98 = "#fff6f5"

[orange]
l10 = "#070200"
l11 = "#090300"
l12 = "#0c0400"
l13 = "#0f0500"
l14 = "#110601"
l15 = "#140801"
l16 = "#170a01"
l17 = "#1a0b01"
l18 = "#1d0d01"
l19 = "#200f02"
l20 = "#231102"
l21 = "#261302"
l22 = "#291502"
l23 = "#2c1703"
l24 = "#301903"
l25 = "#331b04"
l26 = "#361d04"
l27 = "#391f05"
l28 = "#3d2205"
l29 = "#402406"
l30 = "#432607"
l31 = "#472807"
l32 = "#4a2a08"
l33 = "#4d2c09"
l34 = "#512f0a"
l35 = "#54310b"
l36 = "#58330c"
l37 = "#5b350d"
l38 = "#5f380e"
l39 = "#633a0f"
l40 = "#663c10"
l41 = "#6a3f11"
l42 = "#6d4113"
l43 = "#714414"
l44 = "#754615"
l45 = "#784816"
l46 = "#7c4b17"
l47 = "#804d19"
l48 = "#83501a"
l49 = "#87521b"
l50 = "#8b551d"
l51 = "#8e571e"
l52 = "#925a20"
l53 = "#965d22"
l54 = "#995f23"
l55 = "#9d6225"
l56 = "#a16427"
l57 = "#a56729"
l58 = "#a86a2b"
l59 = "#ac6d2d"
l60 = "#af6f2f"
l61 = "#b37231"
l62 = "#b77534"
l63 = "#ba7836"
l64 = "#be7b39"
l65 = "#c17e3c"
l66 = "#c4813f"
l67 = "#c88442"
l68 = "#cb8746"
l69 = "#ce8a49"
l70 = "#d18d4d"
l71 = "#d49152"
l72 = "#d79456"
l73 = "#d9985b"
l74 = "#dc9b5f"
l75 = "#de9f64"
l76 = "#e0a26a"
l77 = "#e2a66f"
l78 = "#e4a975"
l79 = "#e6ad7a"
l80 = "#e8b180"
l81 = "#eab586"
l82 = "#ecb98c"
l83 = "#edbc92"
l84 = "#efc098"
l85 = "#f0c49e"
l86 = "#f1c8a4"
l87 = "#f3ccab"
l88 = "#f4d0b1"
l89 = "#f5d4b7"
l90 = "#f6d8be"
l91 = "#f7dcc4"
l92 = "#f8e0cb"
l93 = "#f9e3d1"
l94 = "#fae7d8"
l95 = "#fbebde"
l96 = "#fcefe5"
l97 = "#fdf3eb"
l98 = "#fef7f2"

[yellow]
l10 = "#040301"
l11 = "#050501"
l12 = "#070601"
l13 = "#080802"
l14 = "#0a0902"
l15 = "#0d0c03"
l16 = "#0f0e04"
l17 = "#111004"
l18 = "#131205"
l19 = "#161406"
l20 = "#181707"
l21 = "#1b1908"
l22 = "#1d1b09"
l23 = "#1f1e0b"
l24 = "#22200c"
l25 = "#24220d"
l26 = "#27250f"
l27 = "#292710"
l28 = "#2c2a11"
l29 = "#2f2c13"
l30 = "#312f14"
l31 = "#343116"
l32 = "#373417"
l33 = "#393719"
l34 = "#3c391a"
l35 = "#3f3c1c"
l36 = "#413e1d"
l37 = "#44411f"
l38 = "#474421"
l39 = "#4a4622"
l40 = "#4d4924"
l41 = "#4f4c25"
l42 = "#524f27"
l43 = "#555129"
l44 = "#58542a"
l45 = "#5b572c"
l46 = "#5e5a2e"
l47 = "#615d2f"
l48 = "#646031"
l49 = "#676233"
l50 = "#6a6535"
l51 = "#6d6836"
l52 = "#706b38"
l53 = "#736e3a"
l54 = "#76713c"
l55 = "#79743e"
l56 = "#7c7740"
l57 = "#7f7a42"
l58 = "#827d44"
l59 = "#858046"
l60 = "#888348"
l61 = "#8b864a"
l62 = "#8e894c"
l63 = "#918c4e"
l64 = "#948f51"
l65 = "#989253"
l66 = "#9b9555"
l67 = "#9e9858"
l68 = "#a19b5b"
l69 = "#a49e5d"
l70 = "#a7a160"
l71 = "#aaa463"
l72 = "#ada866"
l73 = "#b0ab69"
l74 = "#b4ae6d"
l75 = "#b7b171"
l76 = "#bab474"
l77 = "#bdb778"
l78 = "#c0ba7d"
l79 = "#c3be81"
l80 = "#c6c186"
l81 = "#c9c48b"
l82 = "#cbc790"
l83 = "#ceca95"
l84 = "#d1cd9b"
l85 = "#d4d0a1"
l86 = "#d7d4a6"
l87 = "#dad7ac"
l88 = "#dddab2"
l89 = "#e0ddb8"
l90 = "#e2e0bf"
l91 = "#e5e3c5"
l92 = "#e8e6cb"
l93 = "#ebe9d1"
l94 = "#eeecd8"
l95 = "#f1f0de"
l96 = "#f3f3e5"
l97 = "#f6f6eb"
l98 = "#f9f9f2"

[green]
l10 = "#010402"
l11 = "#020602"
l12 = "#020703"
l13 = "#030904"
l14 = "#040c05"
l15 = "#040e06"
l16 = "#051007"
l17 = "#061308"
l18 = "#08150a"
l19 = "#09180b"
l20 = "#0b1a0d"
l21 = "#0c1d0f"
l22 = "#0e1f10"
l23 = "#0f2212"
l24 = "#112414"
l25 = "#122716"
l26 = "#142a18"
l27 = "#162c19"
l28 = "#172f1b"
l29 = "#19321d"
l30 = "#1b351f"
l31 = "#1d3721"
l32 = "#1e3a23"
l33 = "#203d25"
l34 = "#224027"
l35 = "#244329"
l36 = "#26462b"
l37 = "#27492d"
l38 = "#294c2f"
l39 = "#2b4f31"
l40 = "#2d5133"
l41 = "#2f5435"
l42 = "#315737"
l43 = "#335a39"
l44 = "#355e3b"
l45 = "#37613d"
l46 = "#39643f"
l47 = "#3b6742"
l48 = "#3d6a44"
l49 = "#3f6d46"
l50 = "#417048"
l51 = "#43734a"
l52 = "#45764d"
l53 = "#47794f"
l54 = "#497d51"
l55 = "#4b8054"
l56 = "#4e8356"
l57 = "#508658"
l58 = "#52895b"
l59 = "#558d5d"
l60 = "#579060"
l61 = "#599362"
l62 = "#5c9665"
l63 = "#5e9967"
l64 = "#619d6a"
l65 = "#64a06d"
l66 = "#66a36f"
l67 = "#69a672"
l68 = "#6ca975"
l69 = "#6fad78"
l70 = "#72b07b"
l71 = "#75b37e"
l72 = "#79b681"
l73 = "#7cb985"
l74 = "#80bc88"
l75 = "#84bf8c"
l76 = "#87c28f"
l77 = "#8cc593"
l78 = "#90c897"
l79 = "#94ca9b"
l80 = "#99cd9f"
l81 = "#9dd0a3"
l82 = "#a2d3a8"
l83 = "#a7d5ac"
l84 = "#acd8b1"
l85 = "#b1dbb5"
l86 = "#b6ddba"
l87 = "#bbe0bf"
l88 = "#c0e2c3"
l89 = "#c5e5c8"
l90 = "#cae7cd"
l91 = "#cfead2"
l92 = "#d5ecd7"
l93 = "#daeedc"
l94 = "#dff1e1"
l95 = "#e4f3e6"
l96 = "#eaf6eb"
l97 = "#eff8f0"
l98 = "#f4faf5"

[blue]
l10 = "#01030b"
l11 = "#01040f"
l12 = "#020512"
l13 = "#020715"
l14 = "#030819"
l15 = "#030a1c"
l16 = "#040c20"
l17 = "#050e23"
l18 = "#061127"
l19 = "#07132a"
l20 = "#08152e"
l21 = "#091732"
l22 = "#0b1936"
l23 = "#0c1c39"
l24 = "#0d1e3d"
l25 = "#0f2041"
l26 = "#102245"
l27 = "#122549"
l28 = "#13274d"
l29 = "#152a51"
l30 = "#162c55"
l31 = "#182e59"
l32 = "#1a315d"
l33 = "#1b3362"
l34 = "#1d3666"
l35 = "#1f386a"
l36 = "#203b6e"
l37 = "#223d72"
l38 = "#244077"
l39 = "#25437b"
l40 = "#27457f"
l41 = "#294883"
l42 = "#2b4b88"
l43 = "#2c4d8c"
l44 = "#2e5090"
l45 = "#305394"
l46 = "#325599"
l47 = "#34589d"
l48 = "#365ba1"
l49 = "#385ea5"
l50 = "#3a61aa"
l51 = "#3c63ae"
l52 = "#3e66b2"
l53 = "#4169b6"
l54 = "#436cba"
l55 = "#456fbe"
l56 = "#4772c2"
l57 = "#4a75c6"
l58 = "#4c78ca"
l59 = "#4f7bce"
l60 = "#517ed1"
l61 = "#5481d5"
l62 = "#5784d8"
l63 = "#5a87dc"
l64 = "#5d8adf"
l65 = "#608de2"
l66 = "#6390e5"
l67 = "#6794e8"
l68 = "#6a97ea"
l69 = "#6e9aed"
l70 = "#719def"
l71 = "#75a1f1"
l72 = "#79a4f3"
l73 = "#7da7f5"
l74 = "#81aaf6"
l75 = "#85aef8"
l76 = "#8ab1f9"
l77 = "#8eb4fa"
l78 = "#92b8fb"
l79 = "#97bbfc"
l80 = "#9bbefd"
l81 = "#a0c1fe"
l82 = "#a5c5ff"
l83 = "#aac8ff"
l84 = "#afcbff"
l85 = "#b4cfff"
l86 = "#b9d2ff"
l87 = "#bed5ff"
l88 = "#c3d8ff"
l89 = "#c8dcff"
l90 = "#cddfff"
l91 = "#d2e2ff"
l92 = "#d7e5ff"
l93 = "#dce9ff"
l94 = "#e1ecff"
l95 = "#e6efff"
l96 = "#ebf2ff"
l97 = "#f0f5ff"
l98 = "#f5f9ff"
