# - META -------------------------------------
# MONOBIOME      :mode=dark :harshness=default
# GRASSLAND              :contrast=WCAG 2.2 AA
#
# pat  ::  < 0-bg-3 > | gra | acc | < 3-fg-0 >
# abs  ::  min -- +15 | +30 | +40 | +50 -- +65
# rel  ::  min -- +15 | +15 | +10 | +10 -- +15
# sys  ::  l20 -- l35 | l50 | l60 | l70 -- l85
# app  ::  l25 -- l40 | l55 | l65 | l75 -- l90

mode         = "dark"
biome        = "grassland"
contrast     = "default"
version      = "f{{version}}"
# --------------------------------------------

# - SYS --------------------------------------
bg0          = "f{{grassland.l20}}"  # < MIN >
bg1          = "f{{grassland.l25}}"  # < +05 >
bg2          = "f{{grassland.l30}}"  # < +10 >
bg3          = "f{{grassland.l35}}"  # < +15 >

grey         = "f{{grassland.l50}}"  # < +30 >

red          = "f{{red.l60}}"        # < +40 >
orange       = "f{{orange.l60}}"     # < +40 >
yellow       = "f{{yellow.l60}}"     # < +40 >
green        = "f{{green.l60}}"      # < +40 >
cyan         = "f{{green.l60}}"      # < +40 >
blue         = "f{{blue.l60}}"       # < +40 >
violet       = "f{{blue.l60}}"       # < +40 >
magenta      = "f{{red.l60}}"        # < +40 >

fg3          = "f{{grassland.l70}}"  # < +50 >
fg2          = "f{{grassland.l75}}"  # < +55 >
fg1          = "f{{grassland.l80}}"  # < +60 >
fg0          = "f{{grassland.l85}}"  # < MAX >
# --------------------------------------------

# - APP --------------------------------------
[term]
foreground   = "f{{grassland.l90}}"  # < MAX >
selection_fg = "f{{grassland.l85}}"  # < -05 >

background   = "f{{grassland.l25}}"  # < MIN >
selection_bg = "f{{grassland.l30}}"  # < +05 >

cursor       = "f{{grassland.l85}}"  # <MAX-5>
cursor_text  = "f{{grassland.l30}}"  # <MIN+5>

[term.normal]
black        = "f{{grassland.l25}}"  # < MIN >
red          = "f{{red.l65}}"        # < +40 >
green        = "f{{green.l65}}"      # < +40 >
yellow       = "f{{yellow.l65}}"     # < +40 >
blue         = "f{{blue.l65}}"       # < +40 >
magenta      = "f{{orange.l65}}"     # < +40 >
cyan         = "f{{blue.l65}}"       # < +40 >
white        = "f{{grassland.l80}}"  # < +55 >

[term.bright]
black        = "f{{grassland.l35}}"  # < +10 >
red          = "f{{red.l75}}"        # < +50 >
green        = "f{{green.l75}}"      # < +50 >
yellow       = "f{{yellow.l75}}"     # < +50 >
blue         = "f{{blue.l75}}"       # < +50 >
magenta      = "f{{orange.l75}}"     # < +50 >
cyan         = "f{{blue.l75}}"       # < +50 >
white        = "f{{grassland.l90}}"  # < MAX >

[vim]
bg0          = "f{{grassland.l25}}"  # < MIN >
bg1          = "f{{grassland.l30}}"  # < +05 >
bg2          = "f{{grassland.l35}}"  # < +10 >
bg3          = "f{{grassland.l40}}"  # < +15 >

grey         = "f{{grassland.l55}}"  # < +30 >

red          = "f{{red.l65}}"        # < +40 >
orange       = "f{{orange.l65}}"     # < +40 >
yellow       = "f{{yellow.l65}}"     # < +40 >
green        = "f{{green.l65}}"      # < +40 >
cyan         = "f{{green.l65}}"      # < +40 >
blue         = "f{{blue.l65}}"       # < +40 >
violet       = "f{{blue.l65}}"       # < +40 >
magenta      = "f{{red.l65}}"        # < +40 >

fg3          = "f{{grassland.l75}}"  # < +50 >
fg2          = "f{{grassland.l80}}"  # < +55 >
fg1          = "f{{grassland.l85}}"  # < +60 >
fg0          = "f{{grassland.l90}}"  # < MAX >
# --------------------------------------------
