version = "1.3.0"

[alpine]
l10 = "#030303"
l11 = "#040404"
l12 = "#060606"
l13 = "#070707"
l14 = "#090909"
l15 = "#0b0b0b"
l16 = "#0d0d0d"
l17 = "#0f0f0f"
l18 = "#121212"
l19 = "#141414"
l20 = "#161616"
l21 = "#181818"
l22 = "#1b1b1b"
l23 = "#1d1d1d"
l24 = "#1f1f1f"
l25 = "#222222"
l26 = "#242424"
l27 = "#262626"
l28 = "#292929"
l29 = "#2b2b2b"
l30 = "#2e2e2e"
l31 = "#303030"
l32 = "#333333"
l33 = "#353535"
l34 = "#383838"
l35 = "#3a3a3a"
l36 = "#3d3d3d"
l37 = "#404040"
l38 = "#424242"
l39 = "#454545"
l40 = "#484848"
l41 = "#4a4a4a"
l42 = "#4d4d4d"
l43 = "#505050"
l44 = "#525252"
l45 = "#555555"
l46 = "#585858"
l47 = "#5b5b5b"
l48 = "#5d5d5d"
l49 = "#606060"
l50 = "#636363"
l51 = "#666666"
l52 = "#696969"
l53 = "#6c6c6c"
l54 = "#6f6f6f"
l55 = "#717171"
l56 = "#747474"
l57 = "#777777"
l58 = "#7a7a7a"
l59 = "#7d7d7d"
l60 = "#808080"
l61 = "#838383"
l62 = "#868686"
l63 = "#898989"
l64 = "#8c8c8c"
l65 = "#8f8f8f"
l66 = "#929292"
l67 = "#959595"
l68 = "#989898"
l69 = "#9b9b9b"
l70 = "#9e9e9e"
l71 = "#a1a1a1"
l72 = "#a4a4a4"
l73 = "#a8a8a8"
l74 = "#ababab"
l75 = "#aeaeae"
l76 = "#b1b1b1"
l77 = "#b4b4b4"
l78 = "#b7b7b7"
l79 = "#bababa"
l80 = "#bebebe"
l81 = "#c1c1c1"
l82 = "#c4c4c4"
l83 = "#c7c7c7"
l84 = "#cacaca"
l85 = "#cecece"
l86 = "#d1d1d1"
l87 = "#d4d4d4"
l88 = "#d7d7d7"
l89 = "#dbdbdb"
l90 = "#dedede"
l91 = "#e1e1e1"
l92 = "#e4e4e4"
l93 = "#e8e8e8"
l94 = "#ebebeb"
l95 = "#eeeeee"
l96 = "#f2f2f2"
l97 = "#f5f5f5"
l98 = "#f8f8f8"

[badlands]
l10 = "#060302"
l11 = "#070303"
l12 = "#090504"
l13 = "#0b0605"
l14 = "#0d0807"
l15 = "#0f0909"
l16 = "#120c0b"
l17 = "#140e0d"
l18 = "#16100f"
l19 = "#181211"
l20 = "#1b1413"
l21 = "#1d1615"
l22 = "#1f1918"
l23 = "#221b1a"
l24 = "#241d1c"
l25 = "#27201f"
l26 = "#292221"
l27 = "#2c2523"
l28 = "#2e2726"
l29 = "#312928"
l30 = "#332c2b"
l31 = "#362e2d"
l32 = "#383130"
l33 = "#3b3332"
l34 = "#3d3635"
l35 = "#403837"
l36 = "#433b3a"
l37 = "#453e3c"
l38 = "#48403f"
l39 = "#4b4342"
l40 = "#4d4644"
l41 = "#504847"
l42 = "#534b4a"
l43 = "#564e4c"
l44 = "#58504f"
l45 = "#5b5352"
l46 = "#5e5654"
l47 = "#615957"
l48 = "#645b5a"
l49 = "#675e5d"
l50 = "#696160"
l51 = "#6c6462"
l52 = "#6f6765"
l53 = "#726a68"
l54 = "#756c6b"
l55 = "#786f6e"
l56 = "#7b7271"
l57 = "#7e7574"
l58 = "#817877"
l59 = "#847b79"
l60 = "#877e7c"
l61 = "#8a817f"
l62 = "#8d8482"
l63 = "#908785"
l64 = "#938a88"
l65 = "#968d8b"
l66 = "#99908e"
l67 = "#9c9391"
l68 = "#9f9694"
l69 = "#a29997"
l70 = "#a59c9a"
l71 = "#a89f9d"
l72 = "#aba2a1"
l73 = "#aea5a4"
l74 = "#b2a8a7"
l75 = "#b5abaa"
l76 = "#b8afad"
l77 = "#bbb2b0"
l78 = "#beb5b3"
l79 = "#c1b8b6"
l80 = "#c5bbba"
l81 = "#c8bebd"
l82 = "#cbc2c0"
l83 = "#cec5c3"
l84 = "#d2c8c6"
l85 = "#d5cbca"
l86 = "#d8cecd"
l87 = "#dbd2d0"
l88 = "#dfd5d3"
l89 = "#e2d8d7"
l90 = "#e5dbda"
l91 = "#e8dfdd"
l92 = "#ece2e0"
l93 = "#efe5e4"
l94 = "#f2e9e7"
l95 = "#f6ecea"
l96 = "#f9efee"
l97 = "#fcf3f1"
l98 = "#fff6f5"

[chaparral]
l10 = "#050301"
l11 = "#070402"
l12 = "#080503"
l13 = "#0a0704"
l14 = "#0c0805"
l15 = "#0f0a07"
l16 = "#110c09"
l17 = "#130e0b"
l18 = "#15110d"
l19 = "#17130f"
l20 = "#1a1511"
l21 = "#1c1713"
l22 = "#1e1a15"
l23 = "#211c18"
l24 = "#231e1a"
l25 = "#26211c"
l26 = "#28231f"
l27 = "#2a2521"
l28 = "#2d2823"
l29 = "#2f2a26"
l30 = "#322d28"
l31 = "#342f2b"
l32 = "#37322d"
l33 = "#3a3430"
l34 = "#3c3732"
l35 = "#3f3935"
l36 = "#413c37"
l37 = "#443f3a"
l38 = "#47413c"
l39 = "#49443f"
l40 = "#4c4642"
l41 = "#4f4944"
l42 = "#524c47"
l43 = "#544f4a"
l44 = "#57514c"
l45 = "#5a544f"
l46 = "#5d5752"
l47 = "#5f5a55"
l48 = "#625c57"
l49 = "#655f5a"
l50 = "#68625d"
l51 = "#6b6560"
l52 = "#6e6863"
l53 = "#716a65"
l54 = "#736d68"
l55 = "#76706b"
l56 = "#79736e"
l57 = "#7c7671"
l58 = "#7f7974"
l59 = "#827c77"
l60 = "#857f7a"
l61 = "#88827d"
l62 = "#8b8580"
l63 = "#8e8882"
l64 = "#918b85"
l65 = "#948e88"
l66 = "#97918b"
l67 = "#9a948e"
l68 = "#9d9791"
l69 = "#a09a95"
l70 = "#a49d98"
l71 = "#a7a09b"
l72 = "#aaa39e"
l73 = "#ada6a1"
l74 = "#b0a9a4"
l75 = "#b3ada7"
l76 = "#b6b0aa"
l77 = "#bab3ad"
l78 = "#bdb6b0"
l79 = "#c0b9b3"
l80 = "#c3bcb7"
l81 = "#c6bfba"
l82 = "#c9c3bd"
l83 = "#cdc6c0"
l84 = "#d0c9c3"
l85 = "#d3ccc7"
l86 = "#d6d0ca"
l87 = "#dad3cd"
l88 = "#ddd6d0"
l89 = "#e0d9d3"
l90 = "#e4ddd7"
l91 = "#e7e0da"
l92 = "#eae3dd"
l93 = "#ede6e1"
l94 = "#f1eae4"
l95 = "#f4ede7"
l96 = "#f7f0ea"
l97 = "#fbf4ee"
l98 = "#fef7f1"

[savanna]
l10 = "#040301"
l11 = "#050502"
l12 = "#060603"
l13 = "#080704"
l14 = "#0a0905"
l15 = "#0c0b06"
l16 = "#0e0e08"
l17 = "#10100a"
l18 = "#12120c"
l19 = "#14140e"
l20 = "#171611"
l21 = "#191913"
l22 = "#1b1b15"
l23 = "#1e1d17"
l24 = "#20201a"
l25 = "#22221c"
l26 = "#25241e"
l27 = "#272721"
l28 = "#2a2923"
l29 = "#2c2c25"
l30 = "#2f2e28"
l31 = "#31312a"
l32 = "#34332d"
l33 = "#36362f"
l34 = "#393832"
l35 = "#3b3b34"
l36 = "#3e3d37"
l37 = "#404039"
l38 = "#43433c"
l39 = "#46453f"
l40 = "#484841"
l41 = "#4b4b44"
l42 = "#4e4d47"
l43 = "#515049"
l44 = "#53534c"
l45 = "#56564f"
l46 = "#595851"
l47 = "#5c5b54"
l48 = "#5e5e57"
l49 = "#61615a"
l50 = "#64645d"
l51 = "#67665f"
l52 = "#6a6962"
l53 = "#6d6c65"
l54 = "#6f6f68"
l55 = "#72726b"
l56 = "#75756e"
l57 = "#787870"
l58 = "#7b7b73"
l59 = "#7e7e76"
l60 = "#818179"
l61 = "#84847c"
l62 = "#87877f"
l63 = "#8a8a82"
l64 = "#8d8d85"
l65 = "#909088"
l66 = "#93938b"
l67 = "#96968e"
l68 = "#999991"
l69 = "#9c9c94"
l70 = "#9f9f97"
l71 = "#a2a29a"
l72 = "#a5a59d"
l73 = "#a9a8a0"
l74 = "#acaba3"
l75 = "#afaea7"
l76 = "#b2b1aa"
l77 = "#b5b5ad"
l78 = "#b8b8b0"
l79 = "#bbbbb3"
l80 = "#bfbeb6"
l81 = "#c2c1b9"
l82 = "#c5c5bd"
l83 = "#c8c8c0"
l84 = "#cbcbc3"
l85 = "#cfcec6"
l86 = "#d2d1c9"
l87 = "#d5d5cd"
l88 = "#d8d8d0"
l89 = "#dcdbd3"
l90 = "#dfded6"
l91 = "#e2e2da"
l92 = "#e5e5dd"
l93 = "#e9e8e0"
l94 = "#ecece3"
l95 = "#efefe7"
l96 = "#f3f2ea"
l97 = "#f6f6ed"
l98 = "#f9f9f1"

[grassland]
l10 = "#020402"
l11 = "#030503"
l12 = "#040704"
l13 = "#050805"
l14 = "#060a07"
l15 = "#080c09"
l16 = "#0a0f0b"
l17 = "#0c110d"
l18 = "#0e130f"
l19 = "#111511"
l20 = "#131713"
l21 = "#151a15"
l22 = "#171c18"
l23 = "#1a1e1a"
l24 = "#1c211c"
l25 = "#1e231f"
l26 = "#212621"
l27 = "#232823"
l28 = "#252a26"
l29 = "#282d28"
l30 = "#2a2f2b"
l31 = "#2d322d"
l32 = "#2f3430"
l33 = "#323732"
l34 = "#343a35"
l35 = "#373c37"
l36 = "#393f3a"
l37 = "#3c413c"
l38 = "#3f443f"
l39 = "#414742"
l40 = "#444944"
l41 = "#474c47"
l42 = "#494f4a"
l43 = "#4c524c"
l44 = "#4f544f"
l45 = "#515752"
l46 = "#545a55"
l47 = "#575d57"
l48 = "#5a5f5a"
l49 = "#5c625d"
l50 = "#5f6560"
l51 = "#626863"
l52 = "#656b65"
l53 = "#686e68"
l54 = "#6b706b"
l55 = "#6d736e"
l56 = "#707671"
l57 = "#737974"
l58 = "#767c77"
l59 = "#797f7a"
l60 = "#7c827d"
l61 = "#7f857f"
l62 = "#828882"
l63 = "#858b85"
l64 = "#888e88"
l65 = "#8b918b"
l66 = "#8e948e"
l67 = "#919791"
l68 = "#949a94"
l69 = "#979d98"
l70 = "#9aa09b"
l71 = "#9da39e"
l72 = "#a0a7a1"
l73 = "#a3aaa4"
l74 = "#a6ada7"
l75 = "#a9b0aa"
l76 = "#adb3ad"
l77 = "#b0b6b0"
l78 = "#b3b9b3"
l79 = "#b6bdb7"
l80 = "#b9c0ba"
l81 = "#bcc3bd"
l82 = "#c0c6c0"
l83 = "#c3c9c3"
l84 = "#c6cdc6"
l85 = "#c9d0ca"
l86 = "#ccd3cd"
l87 = "#d0d6d0"
l88 = "#d3dad3"
l89 = "#d6ddd7"
l90 = "#d9e0da"
l91 = "#dde3dd"
l92 = "#e0e7e0"
l93 = "#e3eae4"
l94 = "#e6ede7"
l95 = "#eaf1ea"
l96 = "#edf4ee"
l97 = "#f0f7f1"
l98 = "#f4fbf4"

[tundra]
l10 = "#020306"
l11 = "#030408"
l12 = "#040609"
l13 = "#05070c"
l14 = "#07090e"
l15 = "#090b10"
l16 = "#0b0d12"
l17 = "#0d0f14"
l18 = "#0f1217"
l19 = "#111419"
l20 = "#13161b"
l21 = "#16181d"
l22 = "#181b20"
l23 = "#1a1d22"
l24 = "#1c1f25"
l25 = "#1f2227"
l26 = "#212429"
l27 = "#23272c"
l28 = "#26292e"
l29 = "#282b31"
l30 = "#2b2e33"
l31 = "#2d3036"
l32 = "#303339"
l33 = "#32353b"
l34 = "#35383e"
l35 = "#373b40"
l36 = "#3a3d43"
l37 = "#3d4046"
l38 = "#3f4248"
l39 = "#42454b"
l40 = "#44484e"
l41 = "#474a51"
l42 = "#4a4d53"
l43 = "#4c5056"
l44 = "#4f5359"
l45 = "#52555c"
l46 = "#55585e"
l47 = "#575b61"
l48 = "#5a5e64"
l49 = "#5d6167"
l50 = "#60636a"
l51 = "#63666d"
l52 = "#65696f"
l53 = "#686c72"
l54 = "#6b6f75"
l55 = "#6e7278"
l56 = "#71757b"
l57 = "#74787e"
l58 = "#777a81"
l59 = "#7a7d84"
l60 = "#7d8087"
l61 = "#80838a"
l62 = "#82868d"
l63 = "#858990"
l64 = "#888c93"
l65 = "#8b8f96"
l66 = "#8e9299"
l67 = "#91959c"
l68 = "#95989f"
l69 = "#989ba2"
l70 = "#9b9fa5"
l71 = "#9ea2a9"
l72 = "#a1a5ac"
l73 = "#a4a8af"
l74 = "#a7abb2"
l75 = "#aaaeb5"
l76 = "#adb1b8"
l77 = "#b0b4bb"
l78 = "#b3b8bf"
l79 = "#b7bbc2"
l80 = "#babec5"
l81 = "#bdc1c8"
l82 = "#c0c4cb"
l83 = "#c3c7cf"
l84 = "#c7cbd2"
l85 = "#caced5"
l86 = "#cdd1d8"
l87 = "#d0d4dc"
l88 = "#d3d8df"
l89 = "#d7dbe2"
l90 = "#dadee6"
l91 = "#dde1e9"
l92 = "#e1e5ec"
l93 = "#e4e8ef"
l94 = "#e7ebf3"
l95 = "#eaeff6"
l96 = "#eef2f9"
l97 = "#f1f5fd"
l98 = "#f5f9ff"

[red]
l10 = "#0d0000"
l11 = "#100000"
l12 = "#130000"
l13 = "#170000"
l14 = "#1a0100"
l15 = "#1e0100"
l16 = "#220101"
l17 = "#250101"
l18 = "#290101"
l19 = "#2d0201"
l20 = "#310201"
l21 = "#350201"
l22 = "#390302"
l23 = "#3d0302"
l24 = "#410302"
l25 = "#450403"
l26 = "#490503"
l27 = "#4d0503"
l28 = "#510604"
l29 = "#560704"
l30 = "#5a0805"
l31 = "#5e0906"
l32 = "#620a06"
l33 = "#670b07"
l34 = "#6b0d08"
l35 = "#6f0e09"
l36 = "#740f0a"
l37 = "#78110b"
l38 = "#7d120c"
l39 = "#81140e"
l40 = "#85150f"
l41 = "#8a1710"
l42 = "#8e1912"
l43 = "#931a13"
l44 = "#971c15"
l45 = "#9b1e16"
l46 = "#a02018"
l47 = "#a4221a"
l48 = "#a8241c"
l49 = "#ad271d"
l50 = "#b1291f"
l51 = "#b52c22"
l52 = "#b92e24"
l53 = "#bd3126"
l54 = "#c13428"
l55 = "#c5372b"
l56 = "#c93a2e"
l57 = "#cd3d31"
l58 = "#d04034"
l59 = "#d44437"
l60 = "#d7473a"
l61 = "#db4b3d"
l62 = "#de4f41"
l63 = "#e15344"
l64 = "#e45748"
l65 = "#e65b4c"
l66 = "#e96050"
l67 = "#eb6454"
l68 = "#ee6859"
l69 = "#f06d5d"
l70 = "#f27262"
l71 = "#f47666"
l72 = "#f67b6b"
l73 = "#f77f70"
l74 = "#f98474"
l75 = "#fa8979"
l76 = "#fc8d7e"
l77 = "#fd9283"
l78 = "#fe9788"
l79 = "#ff9c8d"
l80 = "#ffa193"
l81 = "#ffa699"
l82 = "#ffab9e"
l83 = "#ffb0a4"
l84 = "#ffb5aa"
l85 = "#ffbaaf"
l86 = "#ffbfb5"
l87 = "#ffc4ba"
l88 = "#ffc8c0"
l89 = "#ffcdc5"
l90 = "#ffd2ca"
l91 = "#ffd6d0"
l92 = "#ffdbd5"
l93 = "#ffe0da"
l94 = "#ffe4e0"
l95 = "#ffe9e5"
l96 = "#ffedea"
l97 = "#fff2ef"
l98 = "#fff6f5"

[orange]
l10 = "#070200"
l11 = "#090300"
l12 = "#0c0400"
l13 = "#0f0500"
l14 = "#120600"
l15 = "#140801"
l16 = "#170901"
l17 = "#1a0b01"
l18 = "#1d0d01"
l19 = "#200f01"
l20 = "#231101"
l21 = "#261302"
l22 = "#2a1502"
l23 = "#2d1702"
l24 = "#301903"
l25 = "#331b03"
l26 = "#361d03"
l27 = "#3a1f04"
l28 = "#3d2104"
l29 = "#402305"
l30 = "#442605"
l31 = "#472806"
l32 = "#4a2a07"
l33 = "#4e2c07"
l34 = "#512e08"
l35 = "#553109"
l36 = "#58330a"
l37 = "#5c350b"
l38 = "#5f380c"
l39 = "#633a0d"
l40 = "#673c0e"
l41 = "#6a3f0f"
l42 = "#6e4111"
l43 = "#714312"
l44 = "#754613"
l45 = "#794814"
l46 = "#7c4b16"
l47 = "#804d17"
l48 = "#845018"
l49 = "#87521a"
l50 = "#8b551b"
l51 = "#8f571d"
l52 = "#925a1f"
l53 = "#965c20"
l54 = "#9a5f22"
l55 = "#9d6224"
l56 = "#a16426"
l57 = "#a56728"
l58 = "#a86a2b"
l59 = "#ac6d2d"
l60 = "#af7030"
l61 = "#b37232"
l62 = "#b67535"
l63 = "#b97838"
l64 = "#bd7b3c"
l65 = "#c07e3f"
l66 = "#c38243"
l67 = "#c68547"
l68 = "#c9884b"
l69 = "#cc8b4f"
l70 = "#ce8f53"
l71 = "#d19258"
l72 = "#d3965d"
l73 = "#d69962"
l74 = "#d89d67"
l75 = "#daa06c"
l76 = "#dca471"
l77 = "#dea777"
l78 = "#e0ab7c"
l79 = "#e2af82"
l80 = "#e4b387"
l81 = "#e6b68d"
l82 = "#e7ba93"
l83 = "#e9be99"
l84 = "#ebc29e"
l85 = "#ecc5a4"
l86 = "#eec9aa"
l87 = "#efcdb0"
l88 = "#f1d1b6"
l89 = "#f2d5bc"
l90 = "#f3d9c2"
l91 = "#f5dcc8"
l92 = "#f6e0ce"
l93 = "#f7e4d4"
l94 = "#f8e8da"
l95 = "#faece0"
l96 = "#fbf0e6"
l97 = "#fcf3ec"
l98 = "#fdf7f3"

[yellow]
l10 = "#040301"
l11 = "#050502"
l12 = "#060602"
l13 = "#080803"
l14 = "#0a0904"
l15 = "#0c0c04"
l16 = "#0e0e05"
l17 = "#111006"
l18 = "#131207"
l19 = "#151409"
l20 = "#18170a"
l21 = "#1a190c"
l22 = "#1c1b0d"
l23 = "#1f1e0f"
l24 = "#212011"
l25 = "#242212"
l26 = "#262514"
l27 = "#292715"
l28 = "#2b2a17"
l29 = "#2e2c19"
l30 = "#302f1b"
l31 = "#33311c"
l32 = "#36341e"
l33 = "#383620"
l34 = "#3b3921"
l35 = "#3e3c23"
l36 = "#403e25"
l37 = "#434127"
l38 = "#464429"
l39 = "#49462b"
l40 = "#4b492c"
l41 = "#4e4c2e"
l42 = "#514e30"
l43 = "#545132"
l44 = "#575434"
l45 = "#5a5736"
l46 = "#5c5a38"
l47 = "#5f5c3a"
l48 = "#625f3c"
l49 = "#65623e"
l50 = "#686540"
l51 = "#6b6842"
l52 = "#6e6b44"
l53 = "#716e46"
l54 = "#747149"
l55 = "#77744b"
l56 = "#7a764d"
l57 = "#7d794f"
l58 = "#807c51"
l59 = "#837f54"
l60 = "#868256"
l61 = "#898559"
l62 = "#8c885b"
l63 = "#8f8b5e"
l64 = "#928e60"
l65 = "#959263"
l66 = "#989566"
l67 = "#9c9869"
l68 = "#9f9b6c"
l69 = "#a29e6f"
l70 = "#a5a172"
l71 = "#a8a475"
l72 = "#aba779"
l73 = "#aeaa7c"
l74 = "#b1ad80"
l75 = "#b4b084"
l76 = "#b7b388"
l77 = "#bab78c"
l78 = "#bdba90"
l79 = "#c0bd95"
l80 = "#c3c099"
l81 = "#c6c39e"
l82 = "#c9c6a2"
l83 = "#ccc9a7"
l84 = "#cfccac"
l85 = "#d2d0b1"
l86 = "#d5d3b6"
l87 = "#d8d6bb"
l88 = "#dbd9c0"
l89 = "#dedcc5"
l90 = "#e1dfca"
l91 = "#e4e2cf"
l92 = "#e7e6d4"
l93 = "#eae9da"
l94 = "#edecdf"
l95 = "#f0efe4"
l96 = "#f3f2ea"
l97 = "#f6f5ef"
l98 = "#f9f9f4"

[green]
l10 = "#010402"
l11 = "#020602"
l12 = "#020703"
l13 = "#030904"
l14 = "#040c05"
l15 = "#050e06"
l16 = "#061007"
l17 = "#071309"
l18 = "#08150a"
l19 = "#0a170c"
l20 = "#0c1a0e"
l21 = "#0d1c0f"
l22 = "#0f1f11"
l23 = "#102213"
l24 = "#122415"
l25 = "#142717"
l26 = "#162919"
l27 = "#172c1a"
l28 = "#192f1c"
l29 = "#1b321e"
l30 = "#1d3420"
l31 = "#1e3722"
l32 = "#203a24"
l33 = "#223d26"
l34 = "#243f28"
l35 = "#26422a"
l36 = "#28452c"
l37 = "#2a482e"
l38 = "#2c4b30"
l39 = "#2d4e32"
l40 = "#2f5134"
l41 = "#315437"
l42 = "#335739"
l43 = "#355a3b"
l44 = "#375d3d"
l45 = "#3a603f"
l46 = "#3c6341"
l47 = "#3e6644"
l48 = "#406946"
l49 = "#426c48"
l50 = "#446f4b"
l51 = "#46724d"
l52 = "#49754f"
l53 = "#4b7852"
l54 = "#4d7c54"
l55 = "#507f56"
l56 = "#528259"
l57 = "#54855b"
l58 = "#57885e"
l59 = "#598b60"
l60 = "#5c8e63"
l61 = "#5e9166"
l62 = "#619568"
l63 = "#64986b"
l64 = "#679b6e"
l65 = "#6a9e71"
l66 = "#6da174"
l67 = "#70a477"
l68 = "#73a77a"
l69 = "#76aa7d"
l70 = "#7aad81"
l71 = "#7db084"
l72 = "#81b388"
l73 = "#85b68b"
l74 = "#89b98f"
l75 = "#8dbc93"
l76 = "#91bf96"
l77 = "#95c29a"
l78 = "#99c49e"
l79 = "#9ec7a2"
l80 = "#a2caa6"
l81 = "#a6cdab"
l82 = "#abcfaf"
l83 = "#afd2b3"
l84 = "#b4d5b7"
l85 = "#b8d7bc"
l86 = "#bddac0"
l87 = "#c1ddc4"
l88 = "#c6dfc9"
l89 = "#cbe2cd"
l90 = "#cfe5d1"
l91 = "#d4e7d6"
l92 = "#d9eada"
l93 = "#deeddf"
l94 = "#e2efe3"
l95 = "#e7f2e8"
l96 = "#ecf5ed"
l97 = "#f1f7f1"
l98 = "#f5faf6"

[blue]
l10 = "#01030c"
l11 = "#01040f"
l12 = "#020512"
l13 = "#020716"
l14 = "#020819"
l15 = "#030a1d"
l16 = "#040c20"
l17 = "#040e24"
l18 = "#051028"
l19 = "#06132b"
l20 = "#07152f"
l21 = "#081733"
l22 = "#0a1937"
l23 = "#0b1b3b"
l24 = "#0c1e3f"
l25 = "#0e2043"
l26 = "#0f2247"
l27 = "#11254b"
l28 = "#12274f"
l29 = "#142953"
l30 = "#152c57"
l31 = "#172e5b"
l32 = "#18315f"
l33 = "#1a3364"
l34 = "#1b3668"
l35 = "#1d386c"
l36 = "#1f3b70"
l37 = "#203d75"
l38 = "#224079"
l39 = "#24427d"
l40 = "#254582"
l41 = "#274886"
l42 = "#294a8a"
l43 = "#2b4d8e"
l44 = "#2c5093"
l45 = "#2e5297"
l46 = "#30559b"
l47 = "#3258a0"
l48 = "#345aa4"
l49 = "#365da8"
l50 = "#3860ad"
l51 = "#3a63b1"
l52 = "#3c66b5"
l53 = "#3e69b9"
l54 = "#416cbd"
l55 = "#436ec1"
l56 = "#4571c5"
l57 = "#4874c9"
l58 = "#4a77cd"
l59 = "#4d7ad1"
l60 = "#507dd4"
l61 = "#5280d8"
l62 = "#5584db"
l63 = "#5887de"
l64 = "#5b8ae1"
l65 = "#5f8de4"
l66 = "#6290e7"
l67 = "#6593ea"
l68 = "#6997ec"
l69 = "#6c9aee"
l70 = "#709df0"
l71 = "#74a0f2"
l72 = "#78a4f4"
l73 = "#7ca7f6"
l74 = "#80aaf7"
l75 = "#85aef9"
l76 = "#89b1fa"
l77 = "#8db4fb"
l78 = "#92b8fc"
l79 = "#96bbfd"
l80 = "#9bbefe"
l81 = "#a0c1fe"
l82 = "#a4c5ff"
l83 = "#aac8ff"
l84 = "#afcbff"
l85 = "#b4cfff"
l86 = "#b9d2ff"
l87 = "#bed5ff"
l88 = "#c3d8ff"
l89 = "#c8dcff"
l90 = "#cddfff"
l91 = "#d2e2ff"
l92 = "#d7e5ff"
l93 = "#dce9ff"
l94 = "#e1ecff"
l95 = "#e6efff"
l96 = "#ebf2ff"
l97 = "#f0f5ff"
l98 = "#f5f9ff"
